
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/webapp/bbs
	@mkdir  ../../sea-modules/webapp/bbs
	@mkdir  ../../sea-modules/webapp/bbs/1.0.0
	@cp     dist/*.* ../../sea-modules/webapp/bbs/1.0.0
	@echo
	@echo   "deploy to seajs-modules/webapp/bbs/1.0.0"
	@echo
